[discord]

token = "YOUR_TOKEN_HERE"

[github]

app_id = 00000

private_key = '.ssh/actuarius-key.pem'

# The organization or repository this app is installed to
# This allows commands to be used without specifying the owner/repo
default_installation = 'MinecraftForge'

force_default = false